# Generated by Django 6.0.2 on 2026-02-11 21:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fee_type', models.CharField(choices=[('PERCENTAGE', 'Percentage'), ('FIXED', 'Fixed Amount')], default='PERCENTAGE', max_length=20)),
                ('fee_value', models.DecimalField(decimal_places=2, help_text='Percentage or fixed amount', max_digits=5)),
                ('min_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum fee for percentage-based', max_digits=10, null=True)),
                ('max_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum fee for percentage-based', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'platform_fees',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellar_public_key', models.CharField(max_length=56, unique=True)),
                ('stellar_secret_key', models.CharField(max_length=56)),
                ('available_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_earned', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_withdrawn', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_wallets',
            },
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1.0)])),
                ('stellar_destination', models.CharField(max_length=56)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('stellar_transaction_id', models.CharField(blank=True, max_length=64)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'withdrawal_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stellar_escrow_id', models.CharField(max_length=100, unique=True)),
                ('stellar_contract_id', models.CharField(max_length=100)),
                ('stellar_transaction_hash', models.CharField(max_length=64)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('worker_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('released_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Funding'), ('FUNDED', 'Funded'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('employer_approved', models.BooleanField(default=False)),
                ('worker_approved', models.BooleanField(default=False)),
                ('employer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('worker_approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('funded_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('disputed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='contracts.contract')),
            ],
            options={
                'db_table': 'payment_escrows',
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_esc_status_4ada9b_idx'), models.Index(fields=['stellar_escrow_id'], name='payment_esc_stellar_9daa90_idx')],
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ESCROW_CREATE', 'Escrow Created'), ('ESCROW_FUND', 'Escrow Funded'), ('ESCROW_RELEASE', 'Payment Released'), ('ESCROW_REFUND', 'Payment Refunded'), ('WITHDRAWAL', 'Withdrawal'), ('DEPOSIT', 'Deposit'), ('PLATFORM_FEE', 'Platform Fee')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('worker_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stellar_transaction_id', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('stellar_escrow_id', models.CharField(blank=True, max_length=100)),
                ('stellar_source_account', models.CharField(blank=True, max_length=56)),
                ('stellar_destination_account', models.CharField(blank=True, max_length=56)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('milestone_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='contracts.contract')),
                ('employer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='payment_tra_status_ea288f_idx'), models.Index(fields=['stellar_transaction_id'], name='payment_tra_stellar_62fbba_idx'), models.Index(fields=['contract', 'transaction_type'], name='payment_tra_contrac_351abc_idx'), models.Index(fields=['employer', 'status'], name='payment_tra_employe_c2413a_idx'), models.Index(fields=['worker', 'status'], name='payment_tra_worker__82d234_idx')],
            },
        ),
    ]
