# Generated by Django 6.0.2 on 2026-02-11 21:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_type', models.CharField(choices=[('EMPLOYER_TO_WORKER', 'Employer Rating Worker'), ('WORKER_TO_EMPLOYER', 'Worker Rating Employer')], max_length=30)),
                ('communication_rating', models.IntegerField(help_text='Communication skills', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('professionalism_rating', models.IntegerField(help_text='Professionalism and reliability', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('quality_rating', models.IntegerField(help_text='Quality of work', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('punctuality_rating', models.IntegerField(help_text='Punctuality and timeliness', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('overall_rating', models.FloatField(default=0.0)),
                ('review_text', models.TextField(blank=True, max_length=1000)),
                ('pros', models.TextField(blank=True, help_text='What went well', max_length=500)),
                ('cons', models.TextField(blank=True, help_text='What could be improved', max_length=500)),
                ('would_recommend', models.BooleanField(default=True)),
                ('response_text', models.TextField(blank=True, max_length=1000)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('is_flagged', models.BooleanField(default=False)),
                ('flag_reason', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='contracts.contract')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ratings.rating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='RatingFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('INAPPROPRIATE', 'Inappropriate content'), ('FAKE', 'Fake review'), ('OFFENSIVE', 'Offensive language'), ('IRRELEVANT', 'Irrelevant content'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField(max_length=500)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flagged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_flags', to=settings.AUTH_USER_MODEL)),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='ratings.rating')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_flags',
            },
        ),
        migrations.CreateModel(
            name='RatingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ratings', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('communication_avg', models.FloatField(default=0.0)),
                ('professionalism_avg', models.FloatField(default=0.0)),
                ('quality_avg', models.FloatField(default=0.0)),
                ('punctuality_avg', models.FloatField(default=0.0)),
                ('recommendation_rate', models.FloatField(default=0.0)),
                ('rating_5_count', models.IntegerField(default=0)),
                ('rating_4_count', models.IntegerField(default=0)),
                ('rating_3_count', models.IntegerField(default=0)),
                ('rating_2_count', models.IntegerField(default=0)),
                ('rating_1_count', models.IntegerField(default=0)),
                ('total_reviews_given', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating_summary', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rating_summaries',
            },
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['reviewee', 'overall_rating'], name='ratings_reviewe_b540ac_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['contract', 'rating_type'], name='ratings_contrac_f08c3c_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['created_at'], name='ratings_created_7f1288_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('contract', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='ratingflag',
            unique_together={('rating', 'flagged_by')},
        ),
    ]
