# Generated by Django 6.0.2 on 2026-02-11 21:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('terms', models.TextField(help_text='Full contract terms and conditions')),
                ('special_clauses', models.TextField(blank=True, help_text='Custom clauses agreed by both parties')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('payment_schedule', models.CharField(choices=[('FULL', 'Full Payment Upon Completion'), ('HALF', '50% Advance, 50% Upon Completion'), ('MILESTONE', 'Milestone Based'), ('WEEKLY', 'Weekly Payment')], default='FULL', max_length=20)),
                ('milestone_amounts', models.JSONField(blank=True, default=list, help_text='List of milestone payments')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_hours_per_day', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('working_days', models.JSONField(blank=True, default=list, help_text='Days of week: MON, TUE, WED, THU, FRI, SAT, SUN')),
                ('employer_signed', models.BooleanField(default=False)),
                ('worker_signed', models.BooleanField(default=False)),
                ('employer_signed_at', models.DateTimeField(blank=True, null=True)),
                ('worker_signed_at', models.DateTimeField(blank=True, null=True)),
                ('employer_signature_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('worker_signature_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('contract_file', models.FileField(blank=True, help_text='PDF version of contract', null=True, upload_to='contracts/%Y/%m/%d/')),
                ('contract_hash', models.CharField(blank=True, help_text='SHA256 hash of contract terms', max_length=64)),
                ('escrow_id', models.CharField(blank=True, help_text='Stellar escrow contract ID', max_length=100)),
                ('transaction_hash', models.CharField(blank=True, help_text='Stellar transaction hash', max_length=64)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Signatures'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('TERMINATED', 'Terminated'), ('DISPUTED', 'Disputed')], default='DRAFT', max_length=20)),
                ('is_template', models.BooleanField(default=False, help_text='Is this a template contract?')),
                ('version', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_created', to=settings.AUTH_USER_MODEL)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_employer', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='jobs.job')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts_as_worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contracts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('changes', models.JSONField(help_text='JSON of changes made')),
                ('employer_approved', models.BooleanField(default=False)),
                ('worker_approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amendments', to='contracts.contract')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposed_amendments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_amendments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('due_date', models.DateField()),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('completion_notes', models.TextField(blank=True)),
                ('payment_released', models.BooleanField(default=False)),
                ('payment_tx_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_milestones', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='contracts.contract')),
            ],
            options={
                'db_table': 'contract_milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ContractTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('CLEANING', 'Cleaning'), ('COOKING', 'Cooking'), ('CHILDCARE', 'Childcare'), ('ELDERLY', 'Elderly Care'), ('GARDENING', 'Gardening'), ('OTHER', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('terms', models.TextField(help_text='Standard contract terms')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'contract_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['employer', 'status'], name='contracts_employe_e50117_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['worker', 'status'], name='contracts_worker__e8b9ec_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['job', 'status'], name='contracts_job_id_8329d6_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['contract_hash'], name='contracts_contrac_f34dfc_idx'),
        ),
        migrations.AddIndex(
            model_name='contractmilestone',
            index=models.Index(fields=['contract', 'status'], name='contract_mi_contrac_577d32_idx'),
        ),
    ]
